# Generated by Django 3.2 on 2022-01-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterModelOptions(
            name='contactspage',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерею', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='halls',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашняя страницу', 'verbose_name_plural': 'Домашнюю страница'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Картинку', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницу', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='promotions',
            options={'verbose_name': 'Акцию', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='seance',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
