# Generated by Django 3.2 on 2022-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20220124_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title',
        ),
        migrations.AddField(
            model_name='seoblock',
            name='description_seo',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_seo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Заголовок'),
        ),
    ]
