# Generated by Django 3.2 on 2022-02-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20220202_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='seo_text_ua',
            new_name='seo_text_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='image_ua',
            new_name='image_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_ua',
            new_name='title_uk',
        ),
    ]
