# Generated by Django 3.2 on 2022-02-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20220202_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height', unique=True, upload_to='gallery/', verbose_name='Картинка', width_field='width'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='title_seo',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
    ]
