# Generated by Django 3.2 on 2022-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20220212_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='height',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='width',
            field=models.TextField(null=True),
        ),
    ]
