# Generated by Django 3.2 on 2022-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20220212_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='height',
        ),
        migrations.RemoveField(
            model_name='images',
            name='width',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(unique=True, upload_to='gallery/', verbose_name='Картинка'),
        ),
    ]
