# Generated by Django 3.2 on 2022-02-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20220212_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название новости')),
                ('date_published', models.DateField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(unique=True, upload_to='news/', verbose_name='Главная картинка')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
                ('type', models.CharField(choices=[('news', 'Новость'), ('promotions', 'Акция')], max_length=10, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='seo_block',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
        migrations.AddField(
            model_name='events',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок'),
        ),
        migrations.AddField(
            model_name='events',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок'),
        ),
    ]
