# Generated by Django 3.2 on 2022-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20220219_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='banner',
            field=models.ImageField(blank=True, unique=True, upload_to='halls/banners', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='layout',
            field=models.ImageField(blank=True, unique=True, upload_to='halls/layout', verbose_name='Схема зала'),
        ),
    ]
