# Generated by Django 3.2 on 2022-02-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20220222_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='halls',
        ),
        migrations.AddField(
            model_name='halls',
            name='cinemas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='banner',
            field=models.ImageField(unique=True, upload_to='halls/banners', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='layout',
            field=models.ImageField(unique=True, upload_to='halls/layout', verbose_name='Схема зала'),
        ),
    ]
