# Generated by Django 3.2 on 2022-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20220222_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='type',
        ),
        migrations.AddField(
            model_name='movies',
            name='type_2d',
            field=models.BooleanField(default=True, verbose_name='2D'),
        ),
        migrations.AddField(
            model_name='movies',
            name='type_3d',
            field=models.BooleanField(default=False, verbose_name='3D'),
        ),
        migrations.AddField(
            model_name='movies',
            name='type_imax',
            field=models.BooleanField(default=False, verbose_name='IMAX'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='creation_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
    ]
