# Generated by Django 3.2 on 2022-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20220301_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='movies',
            name='date_premier',
            field=models.DateField(null=True, verbose_name='Дата премьеры'),
        ),
    ]
