# Generated by Django 3.2 on 2022-03-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20220301_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='date_premier',
        ),
        migrations.AlterField(
            model_name='movies',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
