# Generated by Django 3.2 on 2022-03-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20220303_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebanner',
            old_name='banner',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='promotionspagebanner',
            old_name='banner',
            new_name='image',
        ),
    ]
