# Generated by Django 3.2 on 2022-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20220307_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundbanner',
            name='background',
        ),
        migrations.RemoveField(
            model_name='backgroundbanner',
            name='background_image',
        ),
        migrations.AddField(
            model_name='backgroundbanner',
            name='type',
            field=models.CharField(choices=[('back', 'Фон'), ('img', 'Фото')], default=('back', 'Фон'), max_length=20, verbose_name='Тип'),
        ),
    ]
