# Generated by Django 3.2 on 2022-03-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20220308_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='type',
            field=models.CharField(choices=[('back', 'Просто фон'), ('img', 'Фото на фон')], default=('back', 'Просто фон'), max_length=5, verbose_name='Тип'),
        ),
    ]
