# Generated by Django 3.2 on 2022-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_backgroundbanner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='type',
            field=models.CharField(choices=[('BG', 'Просто фон'), ('BI', 'Фото на фон')], default='BG', max_length=2, verbose_name='Тип'),
        ),
    ]
