# Generated by Django 3.2 on 2022-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_alter_backgroundbanner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25, unique=True, verbose_name='Баннер')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('interval', models.IntegerField(choices=[(5, '5сек'), (10, '10сек'), (30, '30сек')], default=(5, '5сек'), verbose_name='Интервал')),
            ],
        ),
    ]
