# Generated by Django 3.2 on 2022-03-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_carouselbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='promotionspagebanner',
            name='activate',
        ),
    ]
