# Generated by Django 3.2 on 2022-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_client_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='mailing/')),
            ],
        ),
    ]
