# Generated by Django 3.2 on 2022-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_templatesmailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='seo_text_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='seo_text_uk',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_uk',
        ),
    ]
