# Generated by Django 4.2.4 on 2023-08-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(unique=True, upload_to='banners/background/', verbose_name='Баннер')),
                ('type', models.CharField(choices=[('BG', 'Просто фон'), ('BI', 'Фото на фон')], default='BG', max_length=2, verbose_name='Тип')),
                ('value', models.CharField(default='banner', max_length=6)),
            ],
            options={
                'verbose_name': 'Баннер задний фон',
                'verbose_name_plural': 'Баннер задний фон',
            },
        ),
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25, unique=True, verbose_name='Баннер')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('interval', models.IntegerField(choices=[(5000, '5сек'), (10000, '10сек'), (30000, '30сек')], default=5000, verbose_name='Интервал')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусель',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кинотеатра')),
                ('description', models.TextField(verbose_name='Описание')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('logo', models.ImageField(unique=True, upload_to='cinema/logo/', verbose_name='Логотип')),
                ('photo', models.ImageField(unique=True, upload_to='cinema/photo/', verbose_name='Фото верхнего баннера')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Галерею',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер зала')),
                ('description', models.TextField(verbose_name='Описание зала')),
                ('layout', models.ImageField(unique=True, upload_to='halls/layout', verbose_name='Схема зала')),
                ('banner', models.ImageField(unique=True, upload_to='halls/banners', verbose_name='Верхний баннер')),
                ('creation_date', models.DateField(auto_now=True, null=True, verbose_name='Дата создания')),
                ('cinemas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.cinema', verbose_name='Кинотеатр')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='banners/home_page/', verbose_name='Баннер')),
                ('url', models.URLField(verbose_name='url')),
                ('text', models.CharField(max_length=150, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Баннер главной верх',
                'verbose_name_plural': 'Баннер главной верх',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(unique=True, upload_to='movies/', verbose_name='Главная картинка')),
                ('link', models.URLField(verbose_name='Ссылка на трейлер')),
                ('date_premier', models.DateField(null=True, verbose_name='Дата премьеры')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('type_3d', models.BooleanField(default=False, verbose_name='3D')),
                ('type_2d', models.BooleanField(default=True, verbose_name='2D')),
                ('type_imax', models.BooleanField(default=False, verbose_name='IMAX')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='PromotionsPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='banners/promotions/', verbose_name='Баннер')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'Баннер акции',
                'verbose_name_plural': 'Баненер акции',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('ticket_price', models.PositiveIntegerField(verbose_name='Цена билета')),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.halls', verbose_name='Зал')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.movies', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('title_seo', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('keywords', models.CharField(max_length=100, verbose_name='Ключевые слова')),
                ('description_seo', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Seo блок',
                'verbose_name_plural': 'Seo блок',
            },
        ),
        migrations.CreateModel(
            name='TemplatesMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='mailing/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('type', models.BooleanField(default=True, verbose_name='Тип(покупка или бронь)')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.seance', verbose_name='Сеанс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_base', models.BooleanField(default=True, verbose_name='Базовая страница')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(unique=True, upload_to='pages/', verbose_name='Главная картинка')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок')),
                ('seo_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='gallery/', verbose_name='Картинка')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Картинку',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=15, verbose_name='')),
                ('phone_number2', models.CharField(max_length=15, verbose_name='')),
                ('active', models.BooleanField(default=True, verbose_name='')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('seo_text', models.TextField(verbose_name='')),
                ('seo_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Домашняя страницу',
                'verbose_name_plural': 'Домашнюю страница',
            },
        ),
        migrations.AddField(
            model_name='halls',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название события')),
                ('date_published', models.DateField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(unique=True, upload_to='news/', verbose_name='Главная картинка')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
                ('type', models.CharField(choices=[('news', 'Новость'), ('promotions', 'Акция')], max_length=10, verbose_name='Тип события')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок')),
                ('seo_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кинотеатра')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('coordinates', models.CharField(max_length=100, verbose_name='Координаты для карты')),
                ('logo', models.ImageField(unique=True, upload_to='pages/contacts/', verbose_name='Логотип')),
                ('seo_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.gallery', verbose_name='Галерея картинок'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.seoblock', verbose_name='SEO блок'),
        ),
    ]
