# Generated by Django 3.2.10 on 2022-01-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220108_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Город пользователя', 'verbose_name_plural': 'Город пользователя'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.town', verbose_name='Город'),
        ),
    ]
