# Generated by Django 3.2 on 2022-01-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220108_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], default='', max_length=5, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, unique=True, verbose_name='Телефон'),
        ),
    ]
