# Generated by Django 3.2 on 2022-01-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
